#pragma once

#define DISPLAY_PROFILE_NAME "ST7789 76x284"
#define DISPLAY_PROFILE_DEFAULT_BACKGROUND "/00.jpg"

#define DISPLAY_PROFILE_NEEDLE_L_X 6
#define DISPLAY_PROFILE_NEEDLE_L_Y 238
#define DISPLAY_PROFILE_NEEDLE_R_X 38
#define DISPLAY_PROFILE_NEEDLE_R_Y 238
#define DISPLAY_PROFILE_NEEDLE_THICKNESS 2
#define DISPLAY_PROFILE_NEEDLE_MAIN_LEN 16
#define DISPLAY_PROFILE_NEEDLE_RED_LEN 8
#define DISPLAY_PROFILE_NEEDLE_CENTER_Y SPRITE_HEIGHT
#define DISPLAY_PROFILE_NEEDLE_MIN_ANGLE -140
#define DISPLAY_PROFILE_NEEDLE_MAX_ANGLE -40
#define DISPLAY_PROFILE_NEEDLE_UP_SPEED 5
#define DISPLAY_PROFILE_NEEDLE_DOWN_SPEED 2

#define DISPLAY_PROFILE_STATION_X 4
#define DISPLAY_PROFILE_STATION_Y 44
#define DISPLAY_PROFILE_TITLE1_X 4
#define DISPLAY_PROFILE_TITLE1_Y 84
#define DISPLAY_PROFILE_TITLE2_X 4
#define DISPLAY_PROFILE_TITLE2_Y 118
#define DISPLAY_PROFILE_BITRATE_X 4
#define DISPLAY_PROFILE_BITRATE_Y 204
#define DISPLAY_PROFILE_IP_X 4
#define DISPLAY_PROFILE_IP_Y 224
#define DISPLAY_PROFILE_CLOCK_X 8
#define DISPLAY_PROFILE_CLOCK_Y 18
#define DISPLAY_PROFILE_VOLUME_X 34
#define DISPLAY_PROFILE_VOLUME_Y 204

#define DISPLAY_PROFILE_COLOR_STATION 0xFEA0
#define DISPLAY_PROFILE_COLOR_TITLE 0xFEA0
#define DISPLAY_PROFILE_COLOR_BITRATE 0xFEA0
#define DISPLAY_PROFILE_COLOR_VOLUME 0xFEA0
#define DISPLAY_PROFILE_COLOR_CLOCK 0x07FF
#define DISPLAY_PROFILE_COLOR_IP 0x07FF
#define DISPLAY_PROFILE_COLOR_NEEDLE_MAIN 0x0000
#define DISPLAY_PROFILE_COLOR_NEEDLE_RED 0xF800
