#pragma once

#define DISPLAY_PROFILE_NAME "Custom Generated"
#define DISPLAY_PROFILE_ROTATION 3
#define DISPLAY_PROFILE_DEFAULT_BACKGROUND "/20260424_001300_0000.jpg"

#define DISPLAY_PROFILE_NEEDLE_L_X 69
#define DISPLAY_PROFILE_NEEDLE_L_Y 157
#define DISPLAY_PROFILE_NEEDLE_R_X 290
#define DISPLAY_PROFILE_NEEDLE_R_Y 157
#define DISPLAY_PROFILE_NEEDLE_THICKNESS 4
#define DISPLAY_PROFILE_NEEDLE_MAIN_LEN 73
#define DISPLAY_PROFILE_NEEDLE_RED_LEN 40
#define DISPLAY_PROFILE_NEEDLE_CENTER_Y 80
#define DISPLAY_PROFILE_NEEDLE_MIN_ANGLE -122
#define DISPLAY_PROFILE_NEEDLE_MAX_ANGLE -50
#define DISPLAY_PROFILE_NEEDLE_UP_SPEED 5
#define DISPLAY_PROFILE_NEEDLE_DOWN_SPEED 2
#define DISPLAY_PROFILE_NEEDLE_LEFT_MIRRORED 0

#define DISPLAY_PROFILE_NEEDLE_ROTATION 0

#define DISPLAY_PROFILE_STATION_X 40
#define DISPLAY_PROFILE_STATION_Y 30
#define DISPLAY_PROFILE_TITLE1_X 40
#define DISPLAY_PROFILE_TITLE1_Y 70
#define DISPLAY_PROFILE_TITLE2_X 40
#define DISPLAY_PROFILE_TITLE2_Y 105
#define DISPLAY_PROFILE_BITRATE_X 15
#define DISPLAY_PROFILE_BITRATE_Y 345
#define DISPLAY_PROFILE_IP_X 15
#define DISPLAY_PROFILE_IP_Y 385
#define DISPLAY_PROFILE_CLOCK_X 410
#define DISPLAY_PROFILE_CLOCK_Y 30
#define DISPLAY_PROFILE_VOLUME_X 200
#define DISPLAY_PROFILE_VOLUME_Y 345

#define DISPLAY_PROFILE_COLOR_STATION 0x00FF
#define DISPLAY_PROFILE_COLOR_TITLE 0x01FF
#define DISPLAY_PROFILE_COLOR_BITRATE 0xFEA0
#define DISPLAY_PROFILE_COLOR_VOLUME 0xFEA0
#define DISPLAY_PROFILE_COLOR_CLOCK 0x07FF
#define DISPLAY_PROFILE_COLOR_IP 0x07FF
#define DISPLAY_PROFILE_COLOR_NEEDLE_MAIN 0x0000
#define DISPLAY_PROFILE_COLOR_NEEDLE_RED 0xF800
