// ============================================
// CSS Styles for Web Interface
// ============================================

#ifndef WEB_INTERFACE_STYLES_H
#define WEB_INTERFACE_STYLES_H

inline String getStyles() {
  return String()
    + "* { margin: 0; padding: 0; box-sizing: border-box; }"
    + "html,body { height: 100%; width: 100%; max-width: 100%; overflow-x: hidden; }"
    + "body { font-family: 'Segoe UI', Arial, sans-serif; background: var(--page-bg); background-size: contain; background-position: center; background-attachment: fixed; background-repeat: no-repeat; color: var(--text); min-height: 100vh; overflow-x: hidden; display: flex; flex-direction: column; }"
    + ".topbar { position: sticky; top: 0; left: 0; width: 100%; max-width: 100vw; min-height: 72px; background: var(--topbar-bg); backdrop-filter: blur(16px); border-bottom: 1px solid var(--line); display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 14px 18px; overflow-x: auto; z-index: 1000; flex-shrink: 0; }"
    + ".brand-block { flex: 0 0 auto; min-width: 220px; }"
    + ".brand-kicker { color: var(--accent); font-size: 11px; letter-spacing: 0.18em; text-transform: uppercase; display: block; margin-bottom: 4px; }"
    + ".brand-title { font-size: 24px; font-weight: 700; letter-spacing: 0.02em; }"
    + ".brand-subtitle { color: var(--muted); font-size: 13px; margin-top: 3px; }"
    + ".menu-strip { display: flex; gap: 8px; align-items: center; flex: 1 1 auto; overflow-x: auto; padding-bottom: 2px; }"
    + ".menu-strip::-webkit-scrollbar { height: 6px; }"
    + ".menu-strip::-webkit-scrollbar-thumb { background: var(--scrollbar-thumb); border-radius: 999px; }"
    + ".menu-item { flex: 0 0 auto; padding: 10px 15px; cursor: pointer; transition: all 0.2s ease; border: 1px solid transparent; display: flex; align-items: center; gap: 8px; border-radius: 999px; white-space: nowrap; color: var(--muted); background: transparent; }"
    + ".menu-item:hover { background: var(--menu-hover-bg); color: var(--text); border-color: var(--line); }"
    + ".menu-item.active { background: var(--menu-active-bg); border-color: var(--menu-active-border); color: var(--menu-active-text); box-shadow: inset 0 0 0 1px var(--menu-active-inset); }"
    + ".menu-icon { font-size: 15px; width: 18px; text-align: center; opacity: 0.95; }"
    + ".main-content { padding: 20px 28px 28px; flex: 1; max-width: 1480px; width: 100%; margin: 0 auto; display: flex; flex-direction: column; min-height: 0; }"
    + ".content-section { display: none; flex: 1; min-height: 0; }"
    + ".content-section.active { display: flex; flex-direction: column; }"
    + "#player.content-section.active { display: flex; flex-direction: column; gap: 2px; }"
    + ".section-shell { display: grid; gap: 20px; }"
    + ".display-sticky-bar { position: sticky; top: 16px; z-index: 990; background: var(--stickybar-bg); border: 1px solid var(--line); border-radius: 18px; padding: 10px 12px; box-shadow: var(--shadow); }"
    + ".display-bar-top { display:flex; align-items:center; justify-content:space-between; gap: 12px; margin-bottom: 6px; }"
    + ".display-sticky-title { color: var(--muted); font-size: 12px; margin-bottom: 0; }"
    + ".screen-btns-sticky { margin-top: 0; flex-wrap: nowrap; overflow-x: auto; white-space: nowrap; }"
    + ".screen-btns-sticky::-webkit-scrollbar { height: 6px; }"
    + ".screen-btns-sticky::-webkit-scrollbar-thumb { background: var(--scrollbar-thumb-soft); border-radius: 999px; }"
    + ".section-grid { display: grid; grid-template-columns: minmax(0, 1.35fr) minmax(320px, 0.95fr); gap: 20px; align-items: start; }"
    + ".files-grid { grid-template-columns: minmax(0, 1.2fr) minmax(0, 1fr); }"
    + ".stack { display: grid; gap: 20px; }"
    + ".hero-card, .section, .playlist-container { background: var(--card-bg); border: 1px solid var(--line); border-radius: 24px; box-shadow: var(--shadow); }"
    + ".hero-card { padding: 24px; }"
    + ".section, .playlist-container { padding: 22px; }"
    + ".section-header { display:flex; justify-content:space-between; align-items:flex-start; gap:12px; margin-bottom:18px; }"
    + ".section-title { font-size: 20px; font-weight: 700; }"
    + ".section-note { color: var(--muted); font-size: 13px; margin-top: 4px; }"
    + ".panel-kicker { display:block; color: var(--accent); font-size:11px; text-transform:uppercase; letter-spacing:0.18em; margin-bottom:10px; }"
    
    /* === Ключевые стили для вертикального растяжения === */
    + ".player-wrapper { flex-shrink: 0; }"
    + ".hero-card { max-width: 900px; margin: 0 auto; }"
    + ".playlist-container.playlist-fill { flex: 1; min-height: 0; display: flex; flex-direction: column; max-width: 900px; margin: 0 auto; width: 100%; }"
    + ".playlist-container.playlist-fill .streams-window { flex: 1; overflow-y: auto; min-height: 0; }"
    
    + ".now-playing h2 { color: var(--muted); font-size: 12px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.22em; }"
    + ".player-topline { display:flex; align-items:stretch; gap: 14px; }"
    + ".player-display { flex: 1 1 auto; min-width: 0; max-width: calc(100% - 146px); padding: 14px 16px; border-radius: 18px; background: var(--player-display-bg); border: 1px solid var(--player-display-border); box-shadow: inset 0 1px 0 var(--player-display-inset); }"
    + ".player-side-actions { flex: 0 0 132px; display:flex; flex-direction:column; gap: 8px; }"
    + ".section-nav-btn { width: 100%; min-height: 52px; border-radius: 999px; border: 1px solid var(--line-strong); background: var(--btn-utility-bg); color: var(--text); font-weight: 700; cursor: pointer; transition: transform 0.18s ease, border-color 0.18s ease, background 0.18s ease; box-shadow: inset 0 0 0 1px var(--btn-utility-inset); }"
    + ".section-nav-btn:hover { transform: translateY(-1px); border-color: var(--screen-btn-active-border); background: var(--btn-utility-active-bg); }"
    + ".section-nav-btn.compact { width: auto; min-height: 40px; padding: 8px 16px; }"
    + ".player-side-btn { min-height: 44px; padding: 8px 10px; font-size: 14px; }"
    + ".screen-split-nav { width: 100%; height: 44px; min-height: 44px; display:grid; grid-template-columns: 1fr 1fr; gap: 0; padding: 0; overflow: hidden; border-radius: 999px; border: 1px solid var(--line-strong); background: var(--btn-utility-bg); box-shadow: inset 0 0 0 1px var(--btn-utility-inset); }"
    + ".screen-split-btn { height: 100%; min-height: 0; border: 0; border-radius: 0; background: transparent; color: var(--text); font-weight: 700; font-size: 18px; padding: 0; cursor: pointer; transition: transform 0.18s ease, background 0.18s ease, color 0.18s ease; }"
    + ".screen-split-btn:hover { background: var(--btn-utility-active-bg); }"
    + ".screen-split-left { border-right: 1px solid var(--line-strong); }"
    + ".station-name { color: var(--text); font-size: 24px; line-height: 1.05; font-weight: 700; white-space: nowrap; overflow: hidden; }"
    + ".station-name span { display:inline-block; min-width:100%; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }"
    // + ".station-name.scrolling span { padding-right: 40px; animation: stationMarquee 10s linear infinite; }" //анимация для длинных названий станций, отключена из-за багов с перерисовкой при обновлении метаданных
    + ".track-line { margin-top: 8px; color: var(--track-color); font-size: 15px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }"
    + ".tech-line { margin-top: 6px; color: var(--muted); font-size: 12px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; letter-spacing: 0.02em; }"
    + ".status-text { display:none; }"
    + ".player-controls { display: flex; gap: 8px; align-items: center; justify-content: center; margin: 16px 0 14px; flex-wrap: nowrap; }"
    + ".player-btn { background: var(--btn-bg); color: var(--btn-text); border: none; width: 56px; height: 56px; border-radius: 50%; font-size: 18px; cursor: pointer; transition: transform 0.18s ease, box-shadow 0.18s ease, background 0.18s ease; box-shadow: var(--btn-shadow); font-weight: 700; display: flex; align-items: center; justify-content: center; padding: 0; }"
    + ".player-btn:hover { transform: translateY(-2px); box-shadow: var(--btn-shadow-hover); }"
    + ".player-btn.primary { background: linear-gradient(180deg, var(--accent), var(--accent-strong)); color: var(--btn-primary-text); width: 64px; height: 64px; }"
    + ".player-btn.utility { background: var(--btn-utility-bg); color: var(--text); border: 1px solid var(--btn-utility-border); box-shadow: inset 0 0 0 1px var(--btn-utility-inset); }"
    + ".player-btn.utility.active { background: var(--btn-utility-active-bg); border-color: var(--btn-utility-active-border); color: var(--btn-utility-active-text); box-shadow: var(--btn-utility-active-shadow); }"

    + ".quick-playlists { position: relative; width: 100%; margin: 0 auto 16px; display: none; }"
    + ".quick-playlists.open { display: block; }"
    + ".playlist-dropdown-list { position: absolute; top: 100%; left: 0; right: 0; background: var(--dropdown-bg); backdrop-filter: blur(8px); border: 1px solid var(--line-strong); border-radius: 16px; max-height: 0; overflow: hidden; opacity: 0; z-index: 1000; transition: all 0.25s ease; box-shadow: var(--shadow); margin-top: 8px; }"
    + ".quick-playlists.open .playlist-dropdown-list { max-height: 300px; opacity: 1; overflow-y: auto; }"
    + ".quick-timer .playlist-dropdown-list { padding: 14px; }"
    + ".timer-dropdown-content { min-height: 0; }"
    + ".timer-dropdown-header { display:flex; justify-content:space-between; align-items:center; gap:12px; color: var(--text); font-size: 14px; font-weight: 600; margin-bottom: 12px; }"
    + ".timer-options { display:grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }"
    + ".timer-option { padding: 10px 12px; border-radius: 12px; border: 1px solid var(--line); background: var(--option-bg); color: var(--text); cursor: pointer; text-align: center; }"
    + ".timer-option.active, .timer-option:hover { background: var(--option-active-bg); border-color: var(--option-active-border); }"
    + ".eq-dropdown-content { display:grid; gap: 12px; }"
    + ".eq-sliders { display:grid; gap: 10px; }"
    + ".eq-slider-row { display:grid; gap: 8px; margin-bottom: 0 !important; color: var(--muted); }"
    + ".eq-slider-row span { display:flex; justify-content:space-between; align-items:center; gap:12px; color: var(--text); font-weight: 600; }"
    + ".eq-slider-row strong { color: var(--accent-strong); min-width: 34px; text-align: right; }"
    + ".number-stepper { display:flex; align-items:center; gap: 8px; margin-top: 8px; }"
    + ".stepper-btn { flex: 0 0 44px; min-width: 44px; min-height: 44px; padding: 0; font-size: 24px; line-height: 1; border-radius: 14px; }"
    + ".number-stepper input[type='number'] { flex: 1 1 auto; min-width: 0; height: 44px; text-align: center; font-weight: 600; }"

    + ".volume-control, .sleep-timer-control, .screen-control { margin-top: 16px; padding: 16px; border-radius: 18px; background: var(--panel-sub-bg); border: 1px solid var(--panel-sub-border); }"
    + ".volume-label { display:flex; justify-content:space-between; gap:12px; color: var(--muted); font-size: 13px; margin-bottom: 10px; }"
    + ".volume-value, .sleep-timer-status { color: var(--text); font-weight: 700; }"
    + ".volume-combo { display:flex; align-items:center; border: 1px solid var(--panel-sub-border); border-radius: 999px; background: var(--player-display-bg); overflow: hidden; min-height: 52px; }"
    + ".volume-step-btn { flex: 0 0 58px; height: 52px; border: none; border-radius: 0; background: transparent; color: var(--text); font-size: 24px; font-weight: 700; box-shadow: none; }"
    + ".volume-step-btn:hover { background: var(--menu-hover-bg); border-color: transparent; }"
    + ".volume-step-btn:first-child { border-right: 1px solid var(--panel-sub-border); }"
    + ".volume-step-btn:last-child { border-left: 1px solid var(--panel-sub-border); }"
    + ".volume-slider-wrap { position: relative; flex: 1 1 auto; min-width: 0; padding: 0 14px; }"
    + ".volume-slider-wrap::after { content: ''; position: absolute; left: 14px; right: 14px; top: 50%; height: 3px; transform: translateY(-50%); border-radius: 999px; background: linear-gradient(90deg, transparent 0%, var(--accent) 18%, var(--accent-strong) 50%, var(--accent) 82%, transparent 100%); pointer-events: none; opacity: 0.95; }"
    + ".volume-slider-wrap input[type='range'] { background: transparent; }"
    + ".screen-btns { display:flex; gap:10px; flex-wrap:wrap; margin-top: 8px; }"
    + ".screen-btn { background: var(--screen-btn-bg); color: var(--text); border: 1px solid var(--line); border-radius: 14px; padding: 10px 14px; cursor: pointer; transition: all 0.2s ease; }"
    + ".screen-btn.active, .screen-btn:hover { border-color: var(--screen-btn-active-border); background: var(--screen-btn-active-bg); }"
    + ".playlist-title { color: var(--text); font-size: 19px; margin-bottom: 14px; }"
    + ".station-item { padding: 6px 10px; margin: 2px 0; border-radius: 12px; background: var(--station-bg); cursor: pointer; transition: transform 0.18s ease, background 0.18s ease, border-color 0.18s ease; display: flex; align-items: center; gap: 12px; border: 1px solid transparent; }"
    + ".station-item:hover { transform: translateX(4px); background: var(--station-hover-bg); border-color: var(--station-hover-border); }"
    + ".station-item.playing { background: var(--station-playing-bg); border-color: var(--station-playing-border); }"
    + ".station-item.pending { background: var(--station-playing-bg); border-color: var(--station-playing-border); box-shadow: inset 0 0 0 1px var(--station-playing-border); }"
    + ".station-index { min-width: 28px; color: var(--muted); font-size: 11px; font-weight: 700; text-align: right; }"
    + ".station-item-text { flex: 1 1 auto; min-width: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }"
    + ".station-actions { flex: 0 0 auto; display:flex; align-items:center; }"
    + ".station-add-btn { width: 34px; height: 34px; border-radius: 10px; border: 1px solid var(--station-add-border); background: var(--station-add-bg); color: var(--station-add-text); font-size: 20px; line-height: 1; padding: 0; display:flex; align-items:center; justify-content:center; }"
    + ".station-add-btn:hover { background: var(--station-add-hover-bg); border-color: var(--station-add-hover-border); }"
    + ".station-bullet { width: 12px; height: 12px; border-radius: 50%; border: 2px solid var(--bullet-border); }"
    + ".station-item.playing .station-bullet { background: var(--good); border-color: var(--good); }"
    + ".station-item.pending .station-bullet { background: var(--good); border-color: var(--good); }"
    + ".playlist-header { display:flex; justify-content:space-between; align-items:flex-start; gap:12px; margin-bottom: 16px; flex-shrink: 0; }"
    + ".playlist-header.compact { margin-bottom: 12px; }"
    + ".playlist-summary { display:flex; align-items:center; gap:12px; width:100%; min-width:0; padding: 10px 12px; border-radius: 14px; background: var(--playlist-summary-bg); border: 1px solid var(--playlist-summary-border); }"
    + ".playlist-summary-main { flex: 1 1 auto; min-width: 0; display: flex; align-items: center; gap: 8px; overflow: hidden; }"
    + ".playlist-summary-marquee { flex:1 1 auto; min-width:0; overflow:hidden; white-space:nowrap; color: var(--text); font-size: 14px; font-weight: 600; }"
    + ".playlist-summary-marquee span { display:inline-block; min-width:100%; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }"
    + ".playlist-summary-marquee.scrolling span { padding-right: 32px; animation: playlistMarquee 10s linear infinite; }"
    + ".playlist-summary-dot { flex: 0 0 auto; color: var(--muted); font-size: 12px; }"
    + ".playlist-summary-count { flex:0 0 auto; color: var(--muted); font-size: 12px; white-space: nowrap; }"
    + ".stream-count-short { display:none; }"
    + ".playlist-summary-actions { flex: 0 0 auto; display:flex; align-items:center; gap:8px; margin-left: auto; white-space: nowrap; }"
    + ".playlist-summary-edit { flex: 0 0 auto; }"
    + ".playlist-summary-left { margin-right: 4px; }"
    + ".playlist-selector { position: relative; width: min(280px, 100%); }"
    + ".playlist-dropdown-header { background: var(--dropdown-header-bg); border: 1px solid var(--line-strong); border-radius: 16px; padding: 12px 14px; cursor: pointer; display: flex; justify-content: space-between; align-items: center; color: var(--text); }"
    + ".streams-window { overflow-y: auto; overflow-x: hidden; padding-right: 6px; min-width: 0; }"
    + ".streams-window::-webkit-scrollbar { width: 8px; }"
    + ".streams-window::-webkit-scrollbar-thumb { background: var(--scrollbar-thumb-soft); border-radius: 999px; }"
    + ".section h2 { color: var(--text); font-size: 18px; margin-bottom: 10px; }"
    + ".collapsible { overflow: hidden; }"
    + ".collapse-toggle { width: 100%; display:flex; align-items:center; justify-content:space-between; gap:16px; background: transparent; border: none; padding: 0; color: var(--text); font-size: 18px; text-align: left; margin-bottom: 0; }"
    + ".collapse-toggle:hover { background: transparent; border-color: transparent; }"
    + ".collapse-icon { width: 32px; height: 32px; display:inline-flex; align-items:center; justify-content:center; border-radius: 999px; border: 1px solid var(--line-strong); background: var(--collapse-bg); font-size: 20px; line-height: 1; }"
    + ".collapse-content { display: none; margin-top: 18px; }"
    + ".collapsible.open .collapse-content { display: block; }"
    + ".subsection-grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap:20px; }"
    + ".actions-row { display:flex; gap:10px; flex-wrap:wrap; margin-top: 12px; }"
    + ".file-row { display: flex; gap: 10px; margin-bottom: 10px; align-items: center; flex-wrap: wrap; padding: 10px; border-radius: 16px; background: var(--file-row-bg); border: 1px solid var(--file-row-border); }"
    + ".file-btn { flex: 1 1 220px; background: var(--file-btn-bg); color: var(--text); padding: 11px 14px; border-radius: 12px; border: 1px solid var(--line); cursor: pointer; font-weight: 600; }"
    + ".file-btn.selected { background: var(--file-selected-bg); color: var(--file-selected-text); border-color: var(--file-selected-border); }"
    + ".delete-btn { background: var(--delete-bg); color: var(--delete-text); padding: 10px 12px; border-radius: 12px; border: 1px solid var(--delete-border); cursor: pointer; font-size: 13px; }"
    + ".small { padding: 10px 12px; font-size: 13px; border-radius: 12px; background: var(--small-bg); color: var(--text); border: 1px solid var(--line); cursor: pointer; }"
    + ".danger-zone { border-color: var(--danger-border); background: var(--danger-bg); }"
    + ".danger-zone h2, .danger-zone .section-title { color: var(--danger-title); }"
    + "label { color: var(--muted); font-size: 13px; display:block; }"
    + "input[type='range'] { width: 100%; height: 10px; background: var(--range-track-bg); border-radius: 999px; outline: none; -webkit-appearance: none; }"
    + "input[type='range']::-webkit-slider-thumb { -webkit-appearance: none; width: 22px; height: 22px; border-radius: 50%; background: linear-gradient(180deg, var(--accent), var(--accent-strong)); cursor: pointer; border: 2px solid var(--range-thumb-border); box-shadow: var(--range-thumb-shadow); }"
    + "input[type='file'], input[type='submit'], input[type='number'], input[type='text'], input[type='color'], select, button { border-radius: 12px; border: 1px solid var(--line-strong); padding: 11px 12px; font-size: 14px; background: var(--bg-alt); color: var(--text); }"
    + "input[type='submit'], button { background: var(--submit-bg); font-weight: 700; cursor: pointer; transition: all 0.18s ease; }"
    + "input[type='submit']:hover, button:hover { border-color: var(--submit-hover-border); background: var(--submit-hover-bg); }"
    + "input[type='file'] { width: 100%; }"
    + ".settings-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; }"
    + ".setting-item { background: var(--setting-item-bg); padding: 14px; border-radius: 18px; border: 1px solid var(--setting-item-border); }"
    + ".setting-item h3 { font-size: 16px; margin-bottom: 12px; color: var(--text); }"
    + ".setting-item label { margin-bottom: 12px; }"
    + ".inline-settings { display:grid; gap: 12px; }"
    + ".inline-setting-row { display:flex; align-items:center; gap: 12px; flex-wrap: wrap; padding: 12px 14px; border-radius: 16px; background: var(--setting-item-bg); border: 1px solid var(--setting-item-border); }"
    + ".inline-setting-title { flex: 0 0 132px; color: var(--text); font-weight: 700; }"
    + ".inline-setting-controls { flex: 1 1 520px; display:flex; align-items:center; gap: 12px; flex-wrap: wrap; min-width: 0; }"
    + ".inline-slider { display:flex; align-items:center; gap: 8px; flex: 1 1 180px; min-width: 160px; margin-bottom: 0 !important; color: var(--muted); }"
    + ".inline-slider span { flex: 0 0 auto; min-width: 40px; text-align: right; color: var(--text); font-weight: 600; }"
    + ".inline-stepper { flex: 1 1 180px; min-width: 180px; }"
    + ".inline-slider-label { display:flex; justify-content:space-between; align-items:center; gap: 8px; margin-bottom: 0 !important; color: var(--muted); }"
    + ".inline-slider-label span { color: var(--text); font-weight: 600; }"
    + ".inline-stepper-control { margin-top: 6px; }"
    + ".inline-color { display:flex; align-items:center; gap: 8px; margin-bottom: 0 !important; color: var(--muted); }"
    + ".inline-color input[type='color'] { width: 52px; min-width: 52px; padding: 6px; }"
    + ".inline-btn { width: auto; white-space: nowrap; }"
    + ".inline-text-input { flex: 1 1 320px; min-width: 220px; }"
    + ".led-panel { margin-top: 12px; display:grid; gap: 12px; }"
    + ".led-panel input[type='number'] { width: 100%; margin-top: 6px; }"
    + ".led-effect-row { display:grid; grid-template-columns: auto minmax(120px, 1fr) auto; gap: 10px; align-items: center; }"
    + ".led-effect-name { min-height: 42px; display:flex; align-items:center; justify-content:center; text-align:center; padding: 10px 12px; border-radius: 12px; background: var(--led-effect-bg); border: 1px solid var(--line); color: var(--text); font-weight: 600; }"
    + ".info-line { display: flex; justify-content: space-between; gap:12px; padding: 13px 14px; background: var(--info-bg); border-radius: 14px; margin: 8px 0; border:1px solid var(--info-border); }"
    + ".info-label { color: var(--muted); }"
    + ".info-value { color: var(--text); font-weight: 600; text-align:right; }"
    + ".playlist-editor { max-height: 520px; overflow:auto; border:1px solid var(--line); padding:8px; background: var(--playlist-editor-bg); border-radius:18px; }"
    + ".playlist-editor table { width:100%; border-collapse:collapse; }"
    + ".playlist-editor th, .playlist-editor td { padding:10px; border-bottom:1px solid var(--table-row-border); }"
    + ".playlist-editor tr { cursor: pointer; transition: background 0.2s; }"
    + ".playlist-editor tr:hover { background: var(--table-row-hover); }"
    + ".playlist-dropdown-list::-webkit-scrollbar { width: 6px; }"
    + ".playlist-dropdown-list::-webkit-scrollbar-track { background: var(--scrollbar-track); border-radius: 3px; }"
    + ".playlist-dropdown-list::-webkit-scrollbar-thumb { background: var(--scrollbar-thumb); border-radius: 3px; }"
    + ".status-bar { position: fixed; right: 14px; bottom: 14px; max-width: min(420px, calc(100vw - 28px)); background: var(--status-bg); color: var(--status-text); border: 1px solid var(--status-border); border-radius: 16px; padding: 12px 14px; z-index: 1200; display: none; box-shadow: var(--shadow); }"
    + ".status-bar.show { display: block; }"
    + ".status-bar.error { border-color: var(--status-error-border); color: var(--status-error-text); }"
    + ".upload-progress { margin-top: 12px; display: none; }"
    + ".upload-progress.show { display: block; }"
    + ".upload-progress-track { width: 100%; height: 12px; background: var(--upload-track-bg); border-radius: 999px; overflow: hidden; }"
    + ".upload-progress-fill { width: 0%; height: 100%; background: var(--upload-fill-bg); transition: width 0.15s ease; }"
    + ".upload-progress-text { color: var(--muted); margin-top: 8px; font-size: 13px; }"
    + "@media (max-width: 1024px) { .player-row, .section-grid { grid-template-columns: 1fr; } .playlist-selector { width: 100%; } }"
    + "@keyframes playlistMarquee { 0% { transform: translateX(0); } 100% { transform: translateX(-45%); } }"
    + "@keyframes stationMarquee { 0% { transform: translateX(0); } 100% { transform: translateX(-45%); } }"
    + "@media (max-width: 800px) { .main-content { padding: 16px; } .hero-card, .section, .playlist-container { padding: 18px; } .display-sticky-bar { top: 12px; } .files-grid { grid-template-columns: 1fr; } .player-topline { gap: 12px; } .player-side-actions { flex-basis: 112px; } .player-display { max-width: calc(100% - 124px); } }"
    + "@media (max-width: 620px) { .main-content { width: 100%; max-width: 100vw; padding: 10px; } .content-section, .player-row, .stack { width: 100%; min-width: 0; } .display-sticky-bar { top: 8px; padding: 8px 10px; } .player-topline { flex-direction: row; align-items: stretch; } .player-display { max-width: calc(100% - 102px); padding: 12px; } .player-side-actions { flex: 0 0 90px; width: 90px; gap: 5px; } .section-nav-btn { min-height: 38px; } .player-side-btn { min-height: 36px; padding: 5px 6px; font-size: 11px; } .screen-split-nav { height: 36px; min-height: 36px; } .screen-split-btn { font-size: 15px; padding: 0; } .station-name { font-size: 19px; } .track-line { font-size: 13px; } .tech-line { font-size: 11px; } .hero-card, .section, .playlist-container { border-radius: 18px; padding: 12px; width: 100%; min-width: 0; }"
    + ".player-controls { display: flex; gap: 8px; justify-content: space-between; flex-wrap: nowrap; }"
    + ".player-btn { width: 56px; height: 56px; border-radius: 50%; font-size: 18px; padding: 0; }"
    + ".player-btn.primary { width: 60px; height: 60px; }"
    + ".volume-control, .screen-control { padding: 12px; margin-top: 12px; } .volume-label { display: none; } .volume-combo { min-height: 48px; } .volume-step-btn { flex-basis: 52px; height: 48px; } .playlist-summary { padding: 9px 10px; gap: 6px; flex-wrap: nowrap; align-items: center; } .playlist-summary-main { order: 2; flex: 1 1 auto; width: auto; min-width: 0; } .playlist-summary-left { order: 1; margin-right: 0; } .playlist-summary-actions { order: 3; width: auto; justify-content: flex-end; margin-left: 0; gap: 6px; } .playlist-summary-marquee { font-size: 13px; } .playlist-summary-count { display: block; font-size: 11px; } .stream-count-full { display:none; } .stream-count-short { display:inline; } .playlist-summary-dot { display: none; } .playlist-summary-edit { width: auto; padding: 8px 10px; font-size: 12px; } .station-item { padding: 12px; margin: 6px 0; } .streams-window { padding-right: 2px; } .file-row { align-items: stretch; } .file-btn, .small, .delete-btn { width: 100%; } .playlist-summary .small { width: auto; } .info-line { flex-direction: row; align-items: center; } .info-label { flex: 0 0 auto; } .info-value { margin-left: auto; text-align: right; word-break: break-word; } .led-effect-row { grid-template-columns: 1fr; } .inline-setting-row { align-items: flex-start; } .inline-setting-title { flex-basis: 100%; } .inline-setting-controls { flex-basis: 100%; } .inline-slider, .inline-stepper { min-width: 100%; } .inline-text-input { min-width: 100%; } .stepper-btn { flex-basis: 40px; min-width: 40px; min-height: 40px; } .number-stepper input[type='number'] { height: 40px; } }";
}

#endif // WEB_INTERFACE_STYLES_H
